name: Deploy buy runner
on:
  push:
    branches: ["master","develop"]

jobs:

  test: # Название джоб
    runs-on: ubuntu-latest   # Где должна выполняться джоба. 
    steps: # Перечень шагов, которые необходимо выполнить в рамках джоб.
      - name: cd into repo # Название шага
        uses: actions/checkout@v3

  prepare-environment:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Make envfile
        uses: camelCase0/fastapi-trade@v1.0.0
        with:
          envkey_DEBUG: false
          secrets: ${{ toJSON(secrets) }}
          file: .env-non-dev
      - name: Stop and remove containers, networks
        run: ls -la
      - name: Remove unused data
        run: docker system prune -a -f

  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker-compose
        run: docker compose up -d
